defaults:
  - /shared/general_test
environment_name: MiniGrid-BlockedDoorKey-8x8 #options: [MiniGrid-DoorKey-16x16-v0, MiniGrid-FourRooms-v0, MiniGrid-LavaCrossingS11N5-v0, MiniGrid-LavaCrossingS9N3-v0, MiniGrid-Empty-5x5-v0]
# environment_name: MiniGrid-BlockedUnlockPickup-v0 #options: [MiniGrid-DoorKey-16x16-v0, MiniGrid-FourRooms-v0, MiniGrid-LavaCrossingS11N5-v0, MiniGrid-LavaCrossingS9N3-v0, MiniGrid-Empty-5x5-v0]
highlight: False



#constant capturing all types of state attributes in the expert state
#DoorKey {'agent_pos': ['coordinate_width', 'coordinate_height'], 'agent_dir':['agent_dir'], 'goal_pos':['coordinate_width', 'coordinate_height'], 'key_pos':['coordinate_width', 'coordinate_height'], 'door_pos':['coordinate_width', 'coordinate_height'], 'holding_key': ['boolean'], 'door_locked':['boolean'], 'door_open':['boolean'], 'walls':['boolean']}
#DoorKey: [agent_pos, agent_dir, goal_pos, key_pos, door_pos,holding_key, door_locked, door_open, walls]
#BlockedUnlockPickup: [agent_pos, agent_dir, goal_pos, key_pos, door_pos, ball_pos, holding_key, holding_ball, door_locked, door_open, walls]

# state_attributes: [agent_pos, agent_dir, key_pos, holding_key, door_pos, door_locked, door_open, goal_pos]
state_attributes: [agent_pos, agent_dir, key_pos, door_pos, holding_key, door_locked, door_open, ball_pos, holding_ball, goal_pos]
state_attribute_types: {'agent_pos': ['coordinate_width', 'coordinate_height'], 'agent_dir':['agent_dir'], 'goal_pos':['coordinate_width', 'coordinate_height'], 'key_pos':['coordinate_width', 'coordinate_height'], 'door_pos':['coordinate_width', 'coordinate_height'], 'ball_pos': ['coordinate_width', 'coordinate_height'] , 'holding_key': ['boolean'], 'holding_ball': ['boolean'], 'door_locked':['boolean'], 'door_open':['boolean'], 'wall_gaps': ['coordinate_width', 'coordinate_height']}
normalize_state: False


#options: [agent_pos: [x,y], agent_dir: [int], goal_pos: [x,y], key_pos: [x,y], door_pos: [x,y], holding_key: true/false, door_locked: true/false, door_open: true/false]
#agent_dir: 0 - right, 1 - down, 2 - left, 3 - up
controlled_factors: {
  agent_pos: [7,1],
  agent_dir: 1,
  key_pos: [8,3],
  goal_pos: [10,10],
  holding_key: true,
  door_locked: false,
  door_open: true
}
