defaults:
  - /shared/general
environment_name: MiniGrid-Empty-16x16-v0 #options: [MiniGrid-DoorKey-16x16-v0, MiniGrid-FourRooms-v0, MiniGrid-LavaCrossingS11N5-v0, MiniGrid-LavaCrossingS9N3-v0, MiniGrid-Empty-5x5-v0]
max_steps: 5000
highlight: False

#constant capturing all types of state attributes in the expert state
state_attributes: [agent_pos, agent_dir, goal_pos]
state_attribute_types: {'agent_pos': ['coordinate_width', 'coordinate_height'], 'agent_dir':['agent_dir'], 'goal_pos':['coordinate_width', 'coordinate_height']}
normalize_state: False

#options: [agent_pos: [x,y], agent_dir: [int], goal_pos: [x,y], key_pos: [x,y], door_pos: [x,y], holding_key: true/false, door_locked: true/false, door_open: true/false]
#agent_dir: 0 - right, 1 - down, 2 - left, 3 - up
controlled_factors: {
  agent_pos: [7,1],
  agent_dir: 1,
  goal_pos: [10,10],
}

data_generator:
  _target_: data.data_generator.MiniGridDataGenerator
  cfg: ${env} 
